name: Flutter gen_snapshot ARM64

on:
  workflow_dispatch:

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        mode:
          - release
          - profile


    runs-on: ubuntu-latest


    steps:

    - name: Free space
      uses: easimon/maximize-build-space@v4
      with:
        root-reserve-mb: 256
        swap-size-mb: 4096
        remove-dotnet: true
        remove-haskell: true
        remove-android: true


    - uses: actions/checkout@v4


    - name: Dependencies
      run: |

        sudo apt update

        sudo apt install -y \
          git \
          ninja-build \
          clang \
          python3 \
          python-is-python3 \
          zip \
          g++-aarch64-linux-gnu



    - name: depot_tools

      run: |

        git clone --depth=1 \
        https://chromium.googlesource.com/chromium/tools/depot_tools.git

        echo "$PWD/depot_tools" >> $GITHUB_PATH



    - name: Fetch engine

      run: |

        mkdir flutter-engine

        cd flutter-engine


        gclient config \
        --name src/flutter \
        https://github.com/flutter/engine.git


        gclient sync \
        --no-history \
        --shallow



    - name: GN

      run: |

        cd flutter-engine/src


        ./flutter/tools/gn \
          --target-os android \
          --android-cpu arm64 \
          --linux-cpu arm64 \
          --runtime-mode ${{ matrix.mode }} \
          --no-goma \
          --disable-unittests



    - name: Build gen_snapshot only

      run: |

        cd flutter-engine/src


        ninja \
          -C out/android_${{ matrix.mode }}_arm64 \
          gen_snapshot



    - name: Package

      run: |

        mkdir output


        cp \
        flutter-engine/src/out/android_${{ matrix.mode }}_arm64/gen_snapshot \
        output/


        zip \
        gen_snapshot_android_arm64_${{ matrix.mode }}_linux_arm64.zip \
        output/gen_snapshot



    - name: Upload

      uses: actions/upload-artifact@v4

      with:

        name:
          gen_snapshot-${{ matrix.mode }}

        path:
          gen_snapshot_android_arm64_${{ matrix.mode }}_linux_arm64.zip
